### PR TITLE
chore: lint Antora playbooks

### PR DESCRIPTION
**Pull request by lemeurherve**
This PR:
- Adds YAML document start `---`
- Sort and format `start_paths` arrays to avoid "too long line" warning
- Reword comments to avoid "too long line" warning
- Remove trailing spaces

### CODE REVIEW

**Review by krisstern — APPROVED** [review]
LGTM

**Comment by lemeurherve** [comment]
@krisstern can I ask you to me merge my pull requests after review?

There are some times they need some updates, like here where the upstream merge removed a part of the changes of this PR.

Other times I will need to watch and monitor builds, deciding when PR are merged can have its importance.

**Comment by krisstern** [comment]
Sure, no problem @lemeurherve!

**Comment by lemeurherve** [comment]
Thanks!

**Pull request merged**
