### PR TITLE
Update the documentation at site/ for the Gatsby-based jenkins.io website #123

### LINKED ISSUE #123: Update the documentation at site/ for the Gatsby-based jenkins.io website
### Describe your use-case which is not covered by existing documentation.

We currently have a stub as a documentation at https://github.com/jenkins-infra/docs.jenkins.io/blob/main/site/README.md which we will need to either update/add details, which should include (but not necessarily limited to) the following:

1. Change the startup command at [#running-the-project](https://github.com/jenkins-infra/docs.jenkins.io/blob/main/site/README.md#running-the-project) to :
```console
npm run clean && npm run develop
```

2. Add details about which folders are supposed to be generated by running the above command afresh and should be ignored with a ".gitignore" file. 

3. Link up this doc with the [README.adoc at root](https://github.com/jenkins-infra/docs.jenkins.io/blob/main/README.adoc)

4. Add any other details that may be relevant for the Gatsby site. (Open to suggestions!)

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

_No response_

### PR DESCRIPTION
**Pull request by Nwaamaka-Iduwe**
Fixes #123

This pull-request updates the documentation for the Gatsby site hosted in the Jenkins repository. I have made the following changes:

1. Changed the startup command in the README to npm run clean && npm run develop.
2. Added details about the folders generated during the startup process (.cache/ and public/) and included instructions for ignoring these in the .gitignore file.
3. Linked the Gatsby documentation with the root README.adoc for better navigation.
4.Added an overview of Gatsby and information on the project structure to enhance clarity for developers.

### CODE REVIEW

**Comment by krisstern** [comment]
Hi @Nwaamaka-Iduwe thanks for the PR! I noticed you are using your `main` branch instead of a feature branch (one with a name that is not `main`) for the PR. This is not good practice as it prevents the repo maintainer from pushing changes to your branch if you have enabled this and if there is a need to do so.

Let me review this PR shortly.

**Review by krisstern — CHANGES_REQUESTED** [review]
It would be nice if we could update also update the `gatsby build` into `npm run build` in the following line:

https://github.com/jenkins-infra/docs.jenkins.io/blob/611d740ef055fe2b83de71e37e0f869a9073dc7a/site/README.md?plain=1#L98

**Review by krisstern — APPROVED** [review]
LGTM! Thanks for the PR @Nwaamaka-Iduwe

**Comment by Nwaamaka-Iduwe** [comment]
> LGTM! Thanks for the PR @Nwaamaka-Iduwe

Thanks, Krisstern and apologies for doing this on main. Will definitely do better going forward.

**Comment by Nwaamaka-Iduwe** [comment]
Certainly! It's been a year since I contributed here so I had forgotten about that 😅

**Comment by krisstern** [comment]
I see, glad you are back again!

**Comment by Nwaamaka-Iduwe** [comment]
> I see, glad you are back again! 

Thank you!!

**Pull request merged**
