### PR TITLE
Update gitignore and delete auto-generated directories

### PR DESCRIPTION
**Pull request by Vandit1604**
Removed package-lock.json from .gitignore according to npm docs we should include it in the repository

https://docs.npmjs.com/cli/v6/configuring-npm/package-locks#using-locked-packages

### CODE REVIEW

**Comment by krisstern** [comment]
Hi @Vandit1604 I cannot review this PR as it is too big. Could you break this down into smaller pieces so I can check bit-by-bit? 

I think there are some new docs added to the public folder previously since there is no instruction it should not be there in the first place you may have inadvertently deleted with the unwanted files.

**Comment by krisstern** [comment]
Hi @Vandit1604 could you please point out where in https://github.com/jenkins-infra/docs.jenkins.io/blob/main/site/README.md is that instruction located?

**Comment by krisstern** [comment]
It may be implied but not clearly stated

**Comment by Vandit1604** [comment]
The project is structured as follows:

```
.
├── advisories           # Contains Jenkins security advisories and related documentation
├── authors              # Holds information and contributions from community authors
├── content              # Contains general content pages or markdown files for the site
├── data                 # Stores site data such as changelogs, roadmap, events and upgrades used in the project
├── gatsby-browser.js    # Gatsby-specific file for configuring the browser APIs (e.g., handling page transitions)
├── gatsby-config.js     # Main configuration file for Gatsby that defines site metadata, plugins, etc.
├── gatsby-node.js       # Custom Node.js configuration for Gatsby’s build process (e.g., dynamic page creation)
├── gatsby-ssr.jsx       # Server-Side Rendering API configurations to control how the site is rendered on the server
├── node_modules         # Contains installed Node.js packages and dependencies
├── package.json         # NPM package manifest file, lists dependencies, and contains scripts for development/build
├── package-lock.json    # Lockfile that ensures consistent dependency versions across environments
├── public               # Built output of the site, generated after running `gatsby build`
├── README.md            # Project README file, explains how to set up and run the project (documentation)
├── src                  # Source directory containing main site code (e.g., React components, pages, templates)
├── static               # Static files such as images, fonts, and other assets
├── steps                # Contains documentation on Jenkins pipeline steps, with examples and syntax
└── upgrades             # Guides and documents for upgrading Jenkins versions and handling migrations
```

We can also reference: https://www.gatsbyjs.com/docs/reference/gatsby-project-structure/

**Comment by krisstern** [comment]
> > I think there are some new docs added to the public folder previously since there is no instruction it should not be there in the first place you may have inadvertently deleted with the unwanted files.
> 
> People should not add anything in public folder, it is specified in the README.md of `site` directory it is auto-generated from the assets present in `static` directory. If somebody has added something, can you point me at it. I'll move it to the right place.

Hi @Vandit1604 I have already pointed you at these in our DM's on Gitter.

**Comment by Vandit1604** [comment]
What's been done, it's been done. Let's focus on setting things right now?

Public should be gitignored and a npm run clean to remove auto-generated stuff.

Quoting from gatsy documentation:
> `/public`: Automatically generated. The output of the build process will be exposed inside this folder. Should be added to the .gitignore file if not added already.

**Comment by krisstern** [comment]
> The project is structured as follows:
> 
> ```
> .
> ├── advisories           # Contains Jenkins security advisories and related documentation
> ├── authors              # Holds information and contributions from community authors
> ├── content              # Contains general content pages or markdown files for the site
> ├── data                 # Stores site data such as changelogs, roadmap, events and upgrades used in the project
> ├── gatsby-browser.js    # Gatsby-specific file for configuring the browser APIs (e.g., handling page transitions)
> ├── gatsby-config.js     # Main configuration file for Gatsby that defines site metadata, plugins, etc.
> ├── gatsby-node.js       # Custom Node.js configuration for Gatsby’s build process (e.g., dynamic page creation)
> ├── gatsby-ssr.jsx       # Server-Side Rendering API configurations to control how the site is rendered on the server
> ├── node_modules         # Contains installed Node.js packages and dependencies
> ├── package.json         # NPM package manifest file, lists dependencies, and contains scripts for development/build
> ├── package-lock.json    # Lockfile that ensures consistent dependency versions across environments
> ├── public               # Built output of the site, generated after running `gatsby build`
> ├── README.md            # Project README file, explains how to set up and run the project (documentation)
> ├── src                  # Source directory containing main site code (e.g., React components, pages, templates)
> ├── static               # Static files such as images, fonts, and other assets
> ├── steps                # Contains documentation on Jenkins pipeline steps, with examples and syntax
> └── upgrades             # Guides and documents for upgrading Jenkins versions and handling migrations
> ```
> 
> We can also reference: https://www.gatsbyjs.com/docs/reference/gatsby-project-structure/

@Vandit1604 I have already opened a new issue at #123 to follow up on this. There is no further action required on your part about this. Could you please break this PR down into smaller ones? Thanks!

**Comment by krisstern** [comment]
> What's been done, it's been done. Let's focus on setting things right?
> 
> `public` directory should be gitignored and a `npm run clean` to remove auto-generated stuff.
> 
> Quoting from gatsy documentation:
> 
> > `/public`: Automatically generated. The output of the build process will be exposed inside this folder. Should be added to the .gitignore file if not added already.

If you still use questionable language and not follow the community engagement guidelines I will need to remove you from being a maintainer in all repos I oversee.

**Comment by Vandit1604** [comment]
Can you point out where did I not follow the community guidelines and used questionable language while conversing with you?

**Comment by krisstern** [comment]
> Can you point out where did I not follow the community guidelines and used questionable language while conversing with you?

Here: https://www.jenkins.io/project/conduct/#our-standards

**Comment by krisstern** [comment]
PR needs to be broken down into smaller PR's before this can be properly reviewed.

**Comment by krisstern** [comment]
@Vandit1604 The tone of your language is not respectful at all.

**Comment by krisstern** [comment]
@Vandit1604 
Specifically the following sentences you used are derogatory:

Example 1:
> What's been done, it's been done. Let's focus on setting things right?

Example 2:
> Can you point out where did I not follow the community guidelines and used questionable language while conversing with you?

**Comment by krisstern** [comment]
In other words, when you are not being professional and are not dealing witih the subject matter at hand but instead focusing on attacking the person (or picking a fight figuratively speaking), and in a tone that is accusatory, that should be construed as disrespectful speech/behavior.

**Comment by krisstern** [comment]
Hi @Vandit1604 Could you please break this PR now into smaller PR's with incremental changes before I could properly review these? This one is too big for review.

**Comment by Vandit1604** [comment]
@krisstern I have raised https://github.com/jenkins-infra/docs.jenkins.io/pull/144. Please review in your own time.
Thanks

**Comment by gounthar** [comment]
@Vandit1604, I kindly ask you to reconsider your tone.

Your recent comments don't align well with our [code of conduct](https://www.jenkins.io/project/conduct/). While we genuinely appreciate your contributions, I must remind you of the importance of maintaining courtesy in our interactions.

If you're having difficulty recognizing the issue, I encourage you to take a moment to reflect on the feedback from the other contributor who has expressed feeling uncomfortable. Their perspective is valuable and deserves consideration.

As professionals (or future professionals), it's crucial that we maintain a respectful environment. Remember that the attitude we display today can impact our future opportunities and relationships within the community.

Let's work together to foster a positive and inclusive atmosphere for all contributors. If you need any clarification or support in this matter, please don't hesitate to reach out.

Thank you for your understanding and cooperation.

**Comment by Vandit1604** [comment]
@gounthar I’m really sorry if my recent comments didn’t align with the community’s code of conduct. After thinking about it, I realize my tone may have come across in a way that I didn’t intend, and I apologize if it caused any discomfort. 

I understand how important it is to keep things respectful and inclusive, and I really value everyone’s input. From now on, I’ll be more mindful of how my words might be received and will do my best to communicate in a way that reflects the professionalism expected in this community.

Thanks for your understanding and for giving me the chance to learn from this. If there’s anything else I can do to address the situation, please let me know. I look forward to contributing positively moving forward.

Thanks again for your feedback and support!

**Comment by gounthar** [comment]
@Vandit1604, thank you so much for your thoughtful response. 

I truly appreciate your willingness to reflect on the situation and your commitment to improving. Your message demonstrates a great deal of maturity and professionalism. It's not always easy to acknowledge when we've made a misstep, and your openness to feedback is commendable.

Your understanding of the importance of maintaining a respectful and inclusive environment is exactly what makes our community strong. We all have moments where we can improve, and it's how we handle those moments that really matters.

I'm grateful for your continued contributions and your dedication to fostering a positive atmosphere. Your attitude towards growth and learning is invaluable, not just for you, but for our entire community.

Please don't hesitate to reach out if you ever need any support or guidance. We're all here to help each other grow and succeed.

Thank you again for your understanding and your commitment to our community's values. I look forward to our continued collaboration and your future contributions.

Keep up the great work!

**Pull request closed without merging**
