### PR TITLE
feat: update contents 1 june 2024

### PR DESCRIPTION
**Pull request by krisstern**
This PR is to update the contents of the versioned docs to the latest version: `2.452.x`.

### CODE REVIEW

**Review by kmartens27 — COMMENTED** [review]
The changes look okay from the files here, but the deploy does not show any sort of updates to the site or documentation. I am not sure if that is expected behavior, but I am unable to verify the updated site/version in that regard.

**Comment by krisstern** [comment]
Yeah, agreed. It seems like the latest changes are not reflected in the preview.

**Comment by dduportal** [comment]
I don't know if it is related or not but the build on infra.ci.jenkins.io (used for the preview) shows a bunch of errors about image or xref notfound:

```
15:27:10.354] ERROR (asciidoctor): target of image not found: /images/solution-images/jenkins-maven-step.png
...
```

or 

```
[15:27:11.054] ERROR (asciidoctor): target of xref not found: user-docs:installing-jenkins:partial$_docker.adoc
...
```

**Comment by dduportal** [comment]
@krisstern are you able to run the build on your local machine, to see if you see the same behavior?

**Comment by dduportal** [comment]
No obvious reason: I can confirm there are no build error (the preview is published) but I don't know antora well enough to understand why.

Example of page where we can see the behavior (e.g. generated site does not have the updated content: https://deploy-preview-47--docs-jenkins-io.netlify.app/dev-docs/plugin-development/choosing-jenkins-baseline)

**Comment by krisstern** [comment]
Hi @dduportal I think the problem comes from the `Makefile`. Have just updated it in this PR.

**Comment by krisstern** [comment]
@dduportal @kmartens27 I think for the latest changes to show we will need to have the changes pushed to the main branch first.

**Comment by krisstern** [comment]
For the preview site to work I think it will need to be configured so that the branch referred to in either `playbook/antora-playbook.yml` or `playbook/local-antora-playbook.yml` (depending on which one is used) the will match the name of the feature branch, like below:

```yaml
---
site:
  title: Jenkins Docs
  start_page: user-docs::index.adoc

content:
  sources:
    - url: ../
      # Change the branch name to the one you are working on for preview
      branches: [feat/update-contents-1-june-2024]
      start_paths: [docs/solutions, docs/tutorials, docs/user-docs]
      # developer docs are un-versioned that's why they're fetched individually
    - url: ../
      # Change the branch name to the one you are working on for preview
      branches: [eat/update-contents-1-june-2024]
      start_paths:
        [
          docs/about,
          docs/books,
          docs/community,
          docs/dev-docs,
          docs/download,
          docs/events,
          docs/images,
          docs/project,
          docs/projects,
          docs/security,
          docs/sigs,
        ]

runtime:
  cache_dir: ./.cache/antora
  fetch: true
  log:
    level: error

asciidoc:
  attributes:
    page-pagination: ''
    plugin: https://plugins.jenkins.io/
    jira: https://issues.jenkins.io/browse/
    jep: https://github.com/jenkinsci/jep/tree/master/jep/
    matrix: https://matrix.to/#/#
    email: jenkinsci-users@googlegroups.com

ui:
  bundle:
    url: ../ui/build/ui-bundle.zip
    snapshot: true
```

**Comment by dduportal** [comment]
> For the preview site to work I think it will need to be configured so that the branch referred to in either `playbook/antora-playbook.yml` or `playbook/local-antora-playbook.yml` (depending on which one is used) the will match the name of the feature branch, like below:
> 
> ```yaml
> ---
> site:
>   title: Jenkins Docs
>   start_page: user-docs::index.adoc
> 
> content:
>   sources:
>     - url: ../
>       # Change the branch name to the one you are working on for preview
>       branches: [feat/update-contents-1-june-2024]
>       start_paths: [docs/solutions, docs/tutorials, docs/user-docs]
>       # developer docs are un-versioned that's why they're fetched individually
>     - url: ../
>       # Change the branch name to the one you are working on for preview
>       branches: [eat/update-contents-1-june-2024]
>       start_paths:
>         [
>           docs/about,
>           docs/books,
>           docs/community,
>           docs/dev-docs,
>           docs/download,
>           docs/events,
>           docs/images,
>           docs/project,
>           docs/projects,
>           docs/security,
>           docs/sigs,
>         ]
> 
> runtime:
>   cache_dir: ./.cache/antora
>   fetch: true
>   log:
>     level: error
> 
> asciidoc:
>   attributes:
>     page-pagination: ''
>     plugin: https://plugins.jenkins.io/
>     jira: https://issues.jenkins.io/browse/
>     jep: https://github.com/jenkinsci/jep/tree/master/jep/
>     matrix: https://matrix.to/#/#
>     email: jenkinsci-users@googlegroups.com
> 
> ui:
>   bundle:
>     url: ../ui/build/ui-bundle.zip
>     snapshot: true
> ```

Interesting, really good catch @krisstern ! I believe https://docs.antora.org/antora/latest/playbook/content-branches/#current-local-branch might help you on that matter

**Comment by krisstern** [comment]
Thanks @dduportal for the info!

**Comment by krisstern** [comment]
Hi @kmartens27, I think we have fixed the issues with the preview. This PR should be ready for a review.

**Comment by kmartens27** [comment]
Thanks very much @krisstern, I can see the 2.452.x version as expected. However, I wasn't sure if the expected behavior is that the previous version would be gone complete from the documentation. Should the previous 2.426.x still be available, or was it updated in this case, and would it remain going forward, or would it always been updated?
Screenshot 2024-06-12 at 3 54 58 PM

**Comment by krisstern** [comment]
Hi @kmartens27, in order to have multiple versions we will need to have multiple branches with the version number as the branch name. I am intentionally focusing on the main branch now since we were not keeping track of any previous branch and so am calling the most recent branch `main`, until launch. Since I cannot open new branches, I believe that task will fall on someone who does once the versioned docs site go live.

**Comment by kmartens27** [comment]
Ah that makes more sense, thanks very much for clarification @krisstern, much appreciated!

**Review by kmartens27 — APPROVED** [review]
everything looks good here, thanks again @krisstern

**Pull request merged**
