### PR TITLE
Prettier format, padding around content on smaller screens and Tweak Makefile to clean and generate new UI bundle

### PR DESCRIPTION
**Pull request by Vandit1604**
* prettier format
* tweak makefile
* padding around content on smaller screens in docs

### CODE REVIEW

**Comment by hervelemeur** [comment]
This should be 3 distinct pull requests.

**Comment by Vandit1604** [comment]
Closing the PR. 
I'll break down the changes in 3 PRs

**Comment by Vandit1604** [comment]
Divided this PR into #42 #44 #43

**Comment by hervelemeur** [comment]
Thanks!

**Pull request closed without merging**
