### PR TITLE
chore: update `blog/public` to `site/public` in gitignore

### PR DESCRIPTION
**Pull request by Vandit1604**
Raised in place of #118

### CODE REVIEW

**Review by krisstern — CHANGES_REQUESTED** [review]
Hi @Vandit1604 I don't think this would work towards the goal of allowing the reviewer to see which files have been deleted from the `public` folders in an incremental fashsion. This PR should be preceded by a series of incremental PR's to remove each subdirectory and its contents of the `public` folder one-by-one, and not wholesale remove all of these in `.gitignore` without properly removing these files from Git. Please revise your approach to this matter. 

If you have any questions about the requirements please raise them in the PR.

**Comment by Vandit1604** [comment]
Got it. We can start with removing directories that contain the same files in both `public` and `static` directory by using the `diff` tool and raise PRs, removing them one by one for better traceability. 
Let me know if there are any concerns with this approach.

**Comment by Vandit1604** [comment]
Hi @krisstern I've raised https://github.com/jenkins-infra/docs.jenkins.io/pull/147 
Due to the amount of files removed the PR won't be reviewable on GitHub UI.
You will have to check locally with: 
```
$ diff -rq public/images static/images
```

If there's a better way to do this. Please let me know.
Thanks!

**Comment by Vandit1604** [comment]
```
diff -rq public/files static/files
```

also contains same content so nothing is lost here as well if we delete `public/files`

**Pull request closed without merging**
