### PR TITLE
fix: specify width of the Blue Ocean image

### LINKED ISSUE #61: Images on projects/blueocean/about.html are overlapping the TOC
### Describe your use-case which is not covered by existing documentation.

Concerned page: https://docs.jenkins.io/projects/blueocean/about.html

Images on the concerned page are taking full width and overlapping the TOC. 

image

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

_No response_

### PR DESCRIPTION
**Pull request by Allan2000-Git**
Fixes #61 

This PR solves the overlapping image with TOC by providing width to the image

### CODE REVIEW

**Comment by Allan2000-Git** [comment]
@Vandit1604 I went through the code file by file and corrected it. Can you provide the steps to run `docs`?

**Comment by krisstern** [comment]
Hi @Allan2000-Git, please refer to https://github.com/jenkins-infra/docs.jenkins.io?tab=readme-ov-file#installing-antora-and-its-prerequisites for instructions on how to run the Antora docs.

**Comment by krisstern** [comment]
I have reviewed this PR, and it does not seem to fix #61 at all. The following is what I see after the change:

Screenshot 2024-10-12 at 11 20 17 PM

Essentially the side menu now would overlap the Blue Ocean image significantly. For example, I would highly advise using responsive dimensions instead of fixed dimenions in pixels instead, if that route is to be pursued.

**Review by krisstern — CHANGES_REQUESTED** [review]
This approach is not working at all. Please revise or close the PR.

**Comment by Allan2000-Git** [comment]
> This approach is not working at all. Please revise or close the PR.

Will make the changes

**Comment by krisstern** [comment]
HI @Allan2000-Git,
Are you still working on this? Looks like someone esle submitted a PR for this just now.

**Comment by Allan2000-Git** [comment]
> HI @Allan2000-Git, Are you still working on this? Looks like someone esle submitted a PR for this just now.

Yes, I'm on it.

**Comment by krisstern** [comment]
If I do not hear back from you in 7 days with a finalised PR I will release the issue to someone else interested.

**Review by krisstern — APPROVED** [review]
Thanks @Allan2000-Git! LGTM

**Pull request merged**
