### PR TITLE
remove public/images

### PR DESCRIPTION
**Pull request by Vandit1604**
In reference to #144 

```sh
$ diff -rq public/images static/images
```

using diff tool the contetn of publicand static/images is identical .

### CODE REVIEW

**Comment by krisstern** [comment]
Hi @Vandit1604, this PR is exactly like the #118 in that there are too many files being moved around in it. Please break this PR down into smaller PR's before I could review it properly.

**Comment by Vandit1604** [comment]
@krisstern I've reduced the size of the PR, but if there are still issues with reviewing the UI, please let me know. Since there are a lot of files, could you advise on the best order to remove them? What would be the most effective way to proceed?

**Comment by krisstern** [comment]
Hi @Vandit1604 This PR looks really good! Thanks for the follow-up... It would be good if you could open subsequent PR's to remove the files in the `public` directory batch-by-batch.

**Review by krisstern — APPROVED** [review]
LGTM

**Pull request merged**
