### PR TITLE
feat: Added remaining supporters SVG's from jenkins homepage

### LINKED ISSUE #110: Update the Jumbotron in the Gatsby site homepage
### What feature do you want to see added?

Modify https://github.com/jenkins-infra/docs.jenkins.io/blob/main/site/src/components/Jumbotron.js to display every supporter that is currently displayed on the https://www.jenkins.io/ homepage at the end.

image

### PR DESCRIPTION
**Pull request by Allan2000-Git**
## Description

This PR adds a remaining supporters svg's from Jenkins homepage.

Fixes #110  

## Dependencies

No new dependencies introduced.

## Mentions

@Vandit1604 

## Screenshots of relevant screens

After adding all the supporters

Screenshot 2024-10-08 194858

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] My changes in code generate no new warnings
- [x] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

### CODE REVIEW

**Comment by Vandit1604** [comment]
Similarly, Can you add `flex-wrap` and some `gap` for smaller screens.
Currently the site is not very friendly for smaller screens but we need to start somewhere.

**Comment by Allan2000-Git** [comment]
> Similarly, Can you add `flex-wrap` and some `gap` for smaller screens. Currently the site is not very friendly for smaller screens but we need to start somewhere.

@Vandit1604 I have made the changes.

**Comment by Allan2000-Git** [comment]
@Vandit1604 Can you add `hacktoberfest` & `hacktoberfest-aceepted` label?

**Comment by krisstern** [comment]
We will add the `hacktoberfest-accepted` label once we have reviewed this PR within the next few days

**Comment by krisstern** [comment]
Hi @Allan2000-Git, I discovered a major issue if we run `npm run clean && npm run start` after changing directory to the `site` directory at root. The `SVG` images would get deleted automatically. 

You may want to look into this problem deeper and debug before we can accept this PR.

**Comment by Allan2000-Git** [comment]
> Hi @Allan2000-Git, I discovered a major issue if we run `npm run clean && npm run start` after changing directory to the `site` directory at root. The `SVG` images would get deleted automatically.
> 
> You may want to look into this problem deeper and debug before we can accept this PR.

@krisstern Sure, will have a look and make the changes accordingly

**Comment by Vandit1604** [comment]
Store the SVGs in the `static` folder. The public folder is auto generated when we run the project. [This PR](https://github.com/jenkins-infra/docs.jenkins.io/pull/118) removes public folder and gitignores it.

**Comment by Allan2000-Git** [comment]
@krisstern @Vandit1604 I have moved the images to `static` folder

**Comment by krisstern** [comment]
Hi @Allan2000-Git for some reason the GitHub image is not showing for me locally after running `npm run clean && npm run start` in `site/`:

Screenshot 2024-10-11 at 2 00 39 AM

**Comment by Allan2000-Git** [comment]
That's weird. i guess there's some issue with github specific svg. I'll use png as a fallback for github

**Comment by krisstern** [comment]
Hi @Allan2000-Git could you make sure the GitHub image you have shared in the "site/public/images/images/sponsors" and "site/static/images/images/sponsors" are the same? Also, could you check why you have not updated the image file name extension in the below for the GitHub image?: 
https://github.com/jenkins-infra/docs.jenkins.io/blob/8a8d0a9c819e45c857436585612b2546a55ab108/site/src/components/Jumbotron.js#L42

**Comment by krisstern** [comment]
Hi @Allan2000-Git I ihave requested some final changes before I could accept this PR for Hacktoberfest 2024

**Comment by Allan2000-Git** [comment]
> Hi @Allan2000-Git I ihave requested some final changes before I could accept this PR for Hacktoberfest 2024

Hey @krisstern I added `png` as a fallback. I'm not sure why `svg` isn't showing up for only github

**Comment by Allan2000-Git** [comment]
> Hi @Allan2000-Git I ihave requested some final changes before I could accept this PR for Hacktoberfest 2024

Hey @krisstern I fixed the issue. It should be working now.

**Review by krisstern — APPROVED** [review]
Hey @Allan2000-Git, everything looks good now!

**Pull request merged**
