### PR TITLE
chore: clean out site/public folder

### PR DESCRIPTION
**Pull request by krisstern**
### Description
1. Clean out the site/public folder
2. Git ignore the site/public folder
3. Fix up some CSS styling issues in Antora versioned docs

### CODE REVIEW

**Review by gounthar — APPROVED** [review]
That's quite a massive change to review! 🫨

**Comment by krisstern** [comment]
Sorry Bruno, we already trimmed it down somewhat

**Comment by gounthar** [comment]
That's ok, it's just that I can look at the checks, and the deployment, and hope for the best. 😉 
Thank you, Kris. 👍

**Comment by krisstern** [comment]
Thanks @gounthar! Appreciate it

**Pull request merged**
